# Generated by Django 5.1.2 on 2024-11-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_projectelement_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='elements',
            field=models.ManyToManyField(related_name='projects', to='app.projectelement'),
        ),
    ]
