# Generated by Django 5.1.2 on 2024-11-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pricing_remove_material_markup_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='materials',
            field=models.ManyToManyField(related_name='projects', to='app.material'),
        ),
    ]
