# Generated by Django 5.1.2 on 2024-11-02 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_project_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='element',
        ),
        migrations.AddField(
            model_name='material',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='material',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='material',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='app.material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
